import Head from 'next/head'
import Header from '../components/Header'
import Button from '@material-tailwind/react/Button'
import Icon from '@material-tailwind/react/Icon'
import Image from 'next/image'
import { useSession, getSession } from 'next-auth/react'
import Login from '../components/Login'

export default function Home() {
  const { data: session, status } = useSession()

  if (status === 'unauthenticated') return <Login />
  if (status === 'loading') return <Login transition={true} />

  return (
    <div>
      <Head>else
        <title>Document Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <section>
        <div className='max-w-3xl mx-auto bg-[#F8F9FA] px-10'>
          <div className='flex items-center justify-between py-6'>
            <h2 className='text-gray-700'>Start a new document</h2>
            <Button
              className='border-0 mr-2'
              color="gray"
              buttonType="outline"
              rounded={true}
              iconOnly={true}
              ripple="dark"
              aria-label="More options toggle"
            >
              <Icon name="more_vert" color="gray" size="2xl" />
            </Button>
          </div>
          <div>
            <div className='relative h-52 w-40 border-2 cursor-pointer hover:border-blue-600 transition-all duration-150'>
              <Image src="https://links.papareact.com/pju" layout="fill" />
            </div>
            <p className='mt-2 ml-2 text-gray-500 font-semibold'>Blank</p>
          </div>
        </div>
      </section>
      <section className='max-w-3xl mx-auto p-10 text-sm text-gray-700'>
        <header className='flex items-center justify-between'>
          <h2 className='font-medium flex-grow'>My Documents</h2>
          <p className='mr-5'>Date Created</p>
          <Icon name='folder' size="2xl" color='gray' />
        </header>
      </section>
    </div>
  )
}