import { useState } from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import Button from '@material-tailwind/react/Button'
import Icon from '@material-tailwind/react/Icon'
import Image from 'next/image'
import { useSession, getSession } from 'next-auth/react'
import Login from '../components/Login'
import CreateDocModal from '../components/CreateDocModal'
import { useCollection } from 'react-firebase-hooks/firestore'
import { collection, orderBy, query} from 'firebase/firestore'
import { db } from '../firebase'


export default function Home() {
  const { data: session, status } = useSession()
  const [showCreateDocModal, setCreateDocShowModal] = useState(false);

  if (status === 'unauthenticated') return <Login />
  if (status === 'loading') return <Login transition={true} />

  const firestoreQuery = query(collection(collection(db, 'userDocs'), session.user?.email, 'docs'), orderBy('createdAt', 'desc'))

  const [snapshot, isSnapshotLoading] = useCollection(firestoreQuery)

 const documents = !isSnapshotLoading ? snapshot.docs : null

  return (
    <div>
      <Head>
        <title>Document Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <section className='w-full'>
        <div className='max-w-3xl mx-auto bg-[#F8F9FA] px-10'>
          <div className='flex items-center justify-between py-6'>
            <h2 className='text-gray-700'>Start a new document</h2>
            <Button
              className='border-0 mr-2'
              color="gray"
              buttonType="outline"
              rounded={true}
              iconOnly={true}
              ripple="dark"
              aria-label="More options toggle"
            >
              <Icon name="more_vert" color="gray" size="2xl" />
            </Button>
          </div>
          <div>
            <button
              className='focus:outline-none focus:border-blue-600 bg-transparent relative h-52 w-40 border-2 cursor-pointer hover:border-blue-600 transition-all duration-150'
              onClick={() => {
                setCreateDocShowModal(true)
              }}>
              <Image src="https://links.papareact.com/pju" layout="fill" />
            </button>
            <p className='mt-2 ml-2 text-gray-500 font-semibold'>Blank</p>
          </div>
        </div>
      </section>
      <section className='max-w-3xl mx-auto p-10 text-sm text-gray-700'>
        <header className='flex items-center justify-between'>
          <h2 className='font-medium flex-grow'>My Documents</h2>
          <p className='mr-5'>Date Created</p>
          <Icon name='folder' size="2xl" color='gray' />
        </header>
        <section>
              {documents ? documents.map(document => {
                console.log(document)
                return (
                  <li>
                    <Button />
                  </li>
                )
              }) : null} 
          <ul>
          </ul>
        </section>
      </section>
      <CreateDocModal show={showCreateDocModal} setShow={setCreateDocShowModal} />
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context)

  return {
    props: {
      session
    }
  }
}